# Generated by Django 4.2.1 on 2023-10-20 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anketa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50, verbose_name='НАЗВАНИЕ')),
                ('professia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anketa.professia', verbose_name='Профессия')),
            ],
            options={
                'verbose_name': 'Мой новый класс',
                'verbose_name_plural': 'Мой новый класс',
                'ordering': ['-title'],
            },
        ),
    ]
