# Generated by Django 4.2.1 on 2023-10-20 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответ',
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(max_length=50, verbose_name='Пользователь')),
                ('skill', models.TextField(max_length=50, verbose_name='Навык')),
                ('points', models.TextField(max_length=50, verbose_name='Бал')),
                ('date', models.TextField(max_length=50, verbose_name='Дата прохождения')),
            ],
            options={
                'verbose_name': 'Ответы',
                'verbose_name_plural': 'Ответы',
                'ordering': ['-user'],
            },
        ),
        migrations.CreateModel(
            name='ClearSert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50, verbose_name='Название')),
                ('full', models.TextField(max_length=50, verbose_name='Полный')),
                ('one', models.TextField(max_length=50, verbose_name='Одинарный')),
            ],
            options={
                'verbose_name': 'Пустой сертификат',
                'verbose_name_plural': 'Пустой сертификат',
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='Professia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Профессия',
                'verbose_name_plural': 'Профессия',
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навык',
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='Sert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sert', models.TextField(max_length=50, verbose_name='Сертификат')),
                ('user', models.TextField(max_length=50, verbose_name='Пользователь')),
                ('all_skills', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skillallskill', to='anketa.skill', verbose_name='Все навыки')),
                ('key_skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skillkeyskill', to='anketa.skill', verbose_name='Ключевой навык')),
            ],
            options={
                'verbose_name': 'Cертификат',
                'verbose_name_plural': 'Cертификат',
                'ordering': ['-user'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=250, verbose_name='Текст вопроса')),
                ('points', models.TextField(max_length=50, verbose_name='Бал')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anketa.skill', verbose_name='Навык')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопрос',
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='ModelProf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_points', models.TextField(max_length=50, verbose_name='Кол-во балов')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anketa.skill', verbose_name='Навык')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anketa.professia', verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Модельная профессия',
                'verbose_name_plural': 'Модельная профессия',
                'ordering': ['-title'],
            },
        ),
    ]
